### ISSUE TITLE
🐛 [Bug] FX intro example broken

### ISSUE THREAD

**Issue by ncomly-nvidia** [pytorch/TensorRT#1327] opened 2022-08-31 15:05 UTC
##  Bug Description

FX front-end simple example is broken due to API change. Reported by @jaybdub

File /opt/conda/lib/python3.8/site-packages/torch_tensorrt/_compile.py:116, in compile(module, ir, inputs, enabled_precisions, **kwargs) 
    114     lower_precision = LowerPrecision.FP16
    115 elif torch.float32 in enabled_precisions or torch_tensorrt.dtype.float in enabled_precisions:
--> 116     lower_precision = LowerPrecision.FP32
    117 else:
    118     raise ValueError(f"Precision {enabled_precisions} not supported on FX")

NameError: name 'LowerPrecision' is not defined

## To Reproduce

1. Run [this](https://github.com/pytorch/TensorRT/blob/master/examples/fx/torch_trt_simple_example.py) example

## Expected behavior

examples should be stable & in CI

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - NGC 22.08

**Comment by frank-wei** [comment] 2022-08-31 18:19
@jaybdub, I suspect the installation has some problems. Could you try `from torch_tensorrt.fx.utils import LowerPrecision`? How about `import torch_tensorrt.fx`?

**Comment by jaybdub** [comment] 2022-08-31 18:28
Hi @frank-wei ,

Thanks for your reply!

Both of the commands you provided pass, but the example still fails.

I'm using the NGC 22.08 PyTorch container, which ships with torch_tensorrt.

Let me know if anything else needed.

Best,
John

**Comment by frank-wei** [comment] 2022-08-31 18:37
Got it. 
1. How about other fx examples?
2. Are you testing with master branch?

**Comment by ncomly-nvidia** [comment] 2022-09-12 19:52
CC: @narendasan @andi4191

Do we have test cases in DLFW for FX?

**Comment by andi4191** [comment] 2022-09-13 18:38
I think the root cause for this failure is here:
https://github.com/pytorch/TensorRT/blob/release/ngc/22.08/py/torch_tensorrt/_compile.py#L8-L10

@jaybdub: Please uncomment these lines and re-install. You should be able to run it correctly.

I see that this has been resolved in master branch already.

@ncomly-nvidia : We don't have fx frontend test cases in DLFW CI yet. 
@apbose : Please add fx examples to the DLFW CI tests.

**Comment by ncomly-nvidia** [comment] 2022-12-13 16:00
@apbose DLFW tests have been added, correct? Can we confirm this example is tested & works?

**Comment by peri044** [comment] 2022-12-13 23:59
@ncomly-nvidia  FX tests have been added in DLFW and this example works in the latest containers (verified in 22.11).

**Closed** 2022-12-14 15:48 UTC
Labels: bug, component: api [Python], No Activity, fx
