### ISSUE TITLE
Issue with SegResNet based models become slower after converting to TensorRT engine on A100

### ISSUE THREAD

**Issue by Christina-Young-NVIDIA** [pytorch/TensorRT#1669] opened 2023-02-14 18:28 UTC

**Comment by peri044** [comment] 2023-02-28 23:27
Identified the root cause and posted in nv bugs. This is not an issue on our end as per our weekly meeting. Closing it. Please re-open if you have any questions.

**Closed by peri044** 2023-02-28 23:27 UTC
