### ISSUE TITLE
✨[Feature] Create Sample Backend for `torch.compile` for FX path

### ISSUE THREAD

**Issue by gs-olive** [pytorch/TensorRT#1726] opened 2023-03-07 00:26 UTC
## Overview
Create a sample backend, for use in `torch.compile(backend=...)` which compiles the FX graph/subgraphs via fx2trt.

## Context
Instead of requiring each user to specify their own backend to use fx2trt with Dynamo, or requiring use of `torch_tensorrt.fx.compile`, which can encounter issues with symbolically tracing dynamic control flow, provide a canonical, customizable backend for Dynamo which integrates with fx2trt.

## Usage
```python
compiled_model = torch.compile(backend=FX_TRT_BACKEND(**kwargs))(model)
output = compiled_model(inputs)
```

**Comment by Christina-Young-NVIDIA** [comment] 2023-03-27 20:21
Duplicate of https://github.com/pytorch/TensorRT/issues/1717

**Closed** 2023-05-25 00:50 UTC
Labels: feature request
