### ISSUE TITLE
🐛 [Bug] Default dtype for torch_tensorrt.Input is set to _enums.dtype.unknown

### ISSUE THREAD

**Issue by ivan94fi** [pytorch/TensorRT#1686] opened 2023-02-21 10:29 UTC
##  Bug Description

When constructing a `torch_tensorrt.Input` object, if the dtype is not specified it is set to `_enums.dtype.unknown`, while the documentation states that the default dtype is float32.

Relevant lines in source code:
https://github.com/pytorch/TensorRT/blob/deda87bd04e23f0b4cc7cb20bf9be6bd76fcf743/py/torch_tensorrt/_Input.py#L33-L35

Documentation:
https://github.com/pytorch/TensorRT/blob/deda87bd04e23f0b4cc7cb20bf9be6bd76fcf743/docs/v1.3.0/_modules/torch_tensorrt/_Input.html#L384

## To Reproduce

```python
import torch_tensorrt

input_spec = torch_tensorrt.Input(shape=[1, 1, 32, 32])

assert input_spec.dtype == torch_tensorrt._C.dtype.unknown
```

## Expected behavior

The `Input` object should have `float32` dtype as declared in the docs, or the docs should be changed to reflect the actual behavior.

## Environment

> Build information about Torch-TensorRT can be found by turning on debug messages

 - Torch-TensorRT Version (e.g. 1.0.0): 1.3.0
 - PyTorch Version (e.g. 1.0): 1.13.1+cu117
 - CPU Architecture:
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): Installed from torch_tensorrt
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.10.6
 - CUDA version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by gs-olive** [comment] 2023-02-21 23:41
Hello - currently, the frontend `Input` object assigns the data type to `unknown` to indicate the user has not specified a type. The default type of `Float` is then set later in this function (line 40):
https://github.com/pytorch/TensorRT/blob/3467511e8e1e8d60ac1a45ec84b6a5be0cce9cab/py/torch_tensorrt/csrc/tensorrt_classes.cpp#L26-L45
There is currently an issue for centralizing defaults (#1644), which is intended to put all such defaults in a single location.

**Comment by ivan94fi** [comment] 2023-02-22 13:08
Hi, thank you for your response. Our initial problem was that the conversion failed with the following error 
```
RuntimeError: [Error thrown at core/util/trt_util.cpp:296] Expected type to be true but got false
Unsupported ATen data type Double
```
which lead us to conclude that the bug was caused by the `unknown` data type.

After your comment we investigated a bit more and found out that the `unknown` data type is not the problem, as you correctly stated. The error is given in a specific situation:
* no dtype is specified when constructing the `torch_tensorrt.Input` object
* an arithmetic operation (division, multiplication, subtraction, addition) is carried on with the graph's input tensor and a python float constant (which is actually a double in Cpython)

In this case the compile step infers the input tensor dtype as double, which then causes the error reported above (`Unsupported ATen data type Double`). 

An excerpt of the graph level output log where this behavior is observed is reported here:
```
GRAPH: [Torch-TensorRT] - Input to node: %x.1 : Tensor = prim::Param()
GRAPH: [Torch-TensorRT] - Input outputs a Tensor
GRAPH: [Torch-TensorRT] - Input to node: %10 : Tensor = prim::Constant[value={255}]() # /code/smallpixels.core/src/smallpixels/core/networks/server/upscaler/residual_upscaler.py:211:0
GRAPH: [Torch-TensorRT] - Input outputs a Tensor
GRAPH: [Torch-TensorRT] - Input is a constant
GRAPH: [Torch-TensorRT] - Found that constant tensor has type: Double
GRAPH: [Torch-TensorRT] - Estimated input type is Double
DEBUG: [Torch-TensorRT] - Found 1 inputs to graph
DEBUG: [Torch-TensorRT] - Handle input of debug name: x.1
DEBUG: [Torch-TensorRT] - Paring 0: x.1 : Input(shape: [1, 1, 32, 32], dtype: Float32, format: NCHW\Contiguous\Linear)
DEBUG: [Torch-TensorRT] - Found 1 inputs to graph
DEBUG: [Torch-TensorRT] - Handle input of debug name: x.1
DEBUG: [Torch-TensorRT] - In MapInputsAndDetermineDTypes, the g->inputs() size is 1, CollectionInputSpecMap size is1
INFO: [Torch-TensorRT] - Since input type is not explicitly defined, infering using first tensor calculation
  Inferred input x.1 has type Double
Traceback (most recent call last):
  File "trt_issue.py", line 51, in <module>
    trtm = torch_tensorrt.compile(sm, **compile_spec)
  File "/usr/local/lib/python3.8/dist-packages/torch_tensorrt/_compile.py", line 125, in compile
    return torch_tensorrt.ts.compile(
  File "/usr/local/lib/python3.8/dist-packages/torch_tensorrt/ts/_compiler.py", line 136, in compile
    compiled_cpp_mod = _C.compile_graph(module._c, _parse_compile_spec(spec))
RuntimeError: [Error thrown at core/util/trt_util.cpp:296] Expected type to be true but got false
Unsupported ATen data type Double
```

See the complete output log [in this gist](https://gist.github.com/ivan94fi/02f31dc58efcc1a37e4a44876245e0db).

The following code reproduces this case. A very simple `nn.Module` instance is created, where the `forward` method just divides the input tensor (this is important: dividing an intermediate result tensor does not cause the problem) by a constant:
```python
import torch_tensorrt
from torch import nn
import torch

class TestModule(nn.Module):
    def forward(self, x):
        return x / 255.0


x = torch.rand(1, 1, 32, 32).cuda()
m = TestModule()
m.eval().cuda()

sm = torch.jit.trace(m, x)

compile_spec = {
    "inputs": [torch_tensorrt.Input(shape=[1, 1, 32, 32])],
    "enabled_precisions": torch.float16,
    "truncate_long_and_double": True,
    "require_full_compilation": True,
}

with torch_tensorrt.logging.graphs():
    trtm = torch_tensorrt.compile(sm, **compile_spec)

trtm(x)
```

**Comment by gs-olive** [comment] 2023-02-22 20:37
Hello - thank you for the code sample, I am able to reproduce the behavior you have described. After discussing with @narendasan, an updated description of the `Unknown` (unspecified) data type for input tensors is:

- `Unknown` implies the user has not specified an input type, so the compiler first attempts to determine what that type should be based on its usage, as you had mentioned. If this step fails to determine what the type should be, _then_ the compiler will default the input type to `Float32`. If the user disagrees with the inferred type, then a user-specified type (`dtype=torch.float`) will override any inferred data types. In the above case, the compiler inferred the data type of the input should be `Double`, which is an invalid input type for Torch-TRT currently, yielding the error.

The code snippet which infers the data type and performs the user-specified overrides as necessary, is here:
https://github.com/pytorch/TensorRT/blob/835abf0f32a5e3bbcf7ec092be5cc051393a1d08/core/compiler.cpp#L315-L319

**Comment by narendasan** [comment] 2023-02-28 23:40
Closing, reopen if there are still issues

**Closed by narendasan** 2023-02-28 23:40 UTC
Labels: bug

**Comment by chaoz-dev** [comment] 2023-03-01 22:04
@chaoz-dev Tagging myself so I can find this again.
